export const properties = [
  { id: 1, name: "Trailside Towns", location: "Mount Forest, ON", builder: "Wilson Developments", status: "For Sale", priceFrom: 379900, priceTo: 390900, beds: 3, baths: 2, img: "https://images.unsplash.com/photo-1605146769289-440113cc3d00?w=600&q=80", desc: "A thoughtfully planned townhome community nestled against natural green space in Mount Forest, Ontario. Featuring modern architecture and premium finishes throughout." },
  { id: 2, name: "Modal at Main", location: "Cambridge | Reid's Heritage", builder: "Reid's Heritage Homes", status: "For Sale", priceFrom: 499900, priceTo: 589900, beds: 2, baths: 2, img: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&q=80", desc: "Contemporary condominiums in the heart of Cambridge, combining urban convenience with timeless design crafted by Reid's Heritage." },
  { id: 3, name: "Westwind Shores", location: "Ridgeway, Ontario", builder: "Rinaldi Homes", status: "For Sale", priceFrom: 379900, priceTo: 390900, beds: 4, baths: 2, img: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=80", desc: "Discover lakeside living at Westwind Shores — a premier waterfront community offering custom homes with stunning views of Lake Erie." },
  { id: 4, name: "West Creek Townhomes", location: "Hanover, ON", builder: "Reid's Heritage", status: "For Sale", priceFrom: 379900, priceTo: 390900, beds: 4, baths: 2, img: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600&q=80", desc: "Modern townhomes in the growing community of Hanover, offering well-designed layouts with private garages and outdoor spaces." },
  { id: 5, name: "Harvest Oak", location: "Welland, ON", builder: "Mountainview Homes", status: "For Sale", priceFrom: 723900, priceTo: 788900, beds: 4, baths: 3, img: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&q=80", desc: "Premium single-detached homes in Welland's most desirable new community. Harvest Oak blends nature-inspired design with modern comforts." },
  { id: 6, name: "Wellington Way", location: "Mount Forest, ON", builder: "Wilson Developments", status: "For Sale", priceFrom: 449900, priceTo: 529900, beds: 3, baths: 2, img: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=600&q=80", desc: "A new residential enclave in Mount Forest offering spacious family homes with generous lot sizes and contemporary interiors." },
  { id: 7, name: "Summersides Village", location: "Fonthill, ON", builder: "Bayview Wellington", status: "For Sale", priceFrom: 629900, priceTo: 749900, beds: 4, baths: 3, img: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=600&q=80", desc: "An exclusive community in picturesque Fonthill, featuring single-family homes surrounded by parks, trails, and natural amenities." },
  { id: 8, name: "Cityview at Lackner Ridge – Bldg 1", location: "Kitchener, ON", builder: "Activa", status: "For Sale", priceFrom: 399900, priceTo: 489900, beds: 1, baths: 1, img: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&q=80", desc: "High-rise condominium living with panoramic city views in Kitchener's fast-growing Lackner Ridge neighbourhood." },
  { id: 9, name: "The Block on Clair", location: "Guelph, ON", builder: "Reid's Heritage", status: "For Sale", priceFrom: 519900, priceTo: 589900, beds: 2, baths: 2, img: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80", desc: "Urban townhomes and stacked flats in Guelph's south end. The Block on Clair offers sophisticated design with smart, efficient layouts." },
];

export const testimonials = [
  { name: "Arjun & Priya S.", location: "Oakville", text: "Working with Megan and her team at newhomevault.com was the calmest real estate experience we've ever had. We were buying pre-construction and honestly felt overwhelmed at first. Megan explained incentives, timelines, and risks in a way that actually made sense. No pressure. No chaos. Just clarity." },
  { name: "Daniel M.", location: "Whitby", text: "I've worked with agents before, but Megan operates differently. She thinks long term. She helped me evaluate whether a builder deal actually made financial sense instead of just pushing me to sign. That level of honesty stood out. Her team handled the paperwork, builder communication, and follow-ups seamlessly." },
  { name: "Sonia R.", location: "Milton", text: "From our first call, Megan felt steady and informed. We were relocating with two kids and needed someone who understood timelines and logistics. What impressed me most was how clearly she explained the numbers. Incentives, closing costs, market conditions — all broken down without jargon." },
];

export const blogs = [
  { title: "Another Ontario real estate firm has trust accounts frozen by regulator", author: "Amy", category: "Market News", date: "Jun 24, 2026", img: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&q=80", url: "https://globalnews.ca/news/11652435/save-max-real-estate-ontario/" },
  { title: "How the other half rents: taking stock of Canada's high-end rental market", author: "Amy", category: "Interior", date: "Feb 2, 2026", img: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80", url: "https://www.msn.com/en-ca/money/finance-real-estate/how-the-other-half-rents-taking-stock-of-canada-s-high-end-rental-market/ar-AA1VwbRy" },
  { title: "Vancouver Real Estate Rundown: Jan 26 – Feb 1, 2026", author: "Amy", category: "Estate", date: "Feb 2, 2026", img: "https://images.unsplash.com/photo-1448630360428-65456885c650?w=600&q=80", url: "https://howardchai.substack.com/p/vancouver-real-estate-rundown-february-1-2026" },
];
